### ISSUE TITLE
Chagos islands BIOT debate

### ISSUE THREAD

**Issue by RhinosF1** [RhinosF1/newyearsbot#15]
Someone raised that the British don't own Chagos islands.

See https://en.wikipedia.org/wiki/Chagos_Archipelago

> 18:00:29 Happy New Year in Bangladesh (Chittagong, Comilla, Cox’s Bāzār, Dhaka, Jessore, Khulna, Narsingdi, Rajshahi, Rangpur, Tongi), Bhutan (Thimphu), British Indian Ocean Territory, Kazakhstan (Almaty, Astana), Kyrgyzstan (Bishkek, Osh), Russia (Omsk)

**Comment by gerritholl** [comment]
Before granting independence to Mauritius, the United Kingdom dismembered it and forcibly removed the entire population of the Chagos Islands.  The International Court of Justice (ICJ), the United Nations General Assembly, and the International Tribunal for the Law of the Sea have all ruled that sovereignty over the Chagos Islands belongs to Mauritius and not to the United Kingdom. 

So, legally, the case is clear: the Chagos Islands belong to Mauritius.  However, as of 2022-12-31, it remains occupied by the United Kingdom.  I don't know if the newyearsbot has a policy on illegal occupations, but I think it should stick with international law: the Chagos Islands belong to Mauritius, Donbass and Crimea belong to Ukraine, etc.

For more information, see https://en.wikipedia.org/wiki/Chagos_Archipelago_sovereignty_dispute

**Comment by RhinosF1** [comment]
We follow the ISO data.

I have checked 3166 and that uses British Indian Ocean Territory. It looks like a dispute in progress so I will keep an eye.

See https://www.iso.org/obp/ui/#iso:code:3166:IO

**Comment by ugjka** [comment]
It is unlikely  there are any IRC users in Chagos so I'm gonna remove BIOT from my upstream
